version: '3.8'

services:
  frontend:
    build:
      context: ./hello-world
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5172

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5172:5172" 